### PR TITLE
feat(MdDatepicker) Support for field variants

### PR DESCRIPTION
**Pull request by shafimsp**
This PR is to support MdDatepicker with MdField and  its variants

### CODE REVIEW

**Comment by marcosmoura** [comment]
@shafimsp Can you fix the conflicts?

**Comment by shafimsp** [comment]
conflicts fixed

**Comment by shafimsp** [comment]
@marcosmoura i need to merge PR #1601 before resolve these conflicts. its related.

**Comment by shafimsp** [comment]
closing this PR, i have another PR #1667

**Pull request closed without merging**
