### PR TITLE
Component/md table pagination fix and docs

### PR DESCRIPTION
**Pull request by oliver-ni**
New version of #2004

### CODE REVIEW

**Comment by rs-sliske** [comment]
is there any idea when these changes will get merged? or can someone give some tips about running this version?

**Comment by dotbatch** [comment]
Would love to have this feature. Current work arounds are not a good solution.

**Comment by PauloJFCabral** [comment]
Can you merge this please?

**Comment by Tropicalista** [comment]
@marqbeniamin Can you tell me when this will be merged? It's the only feature missing on my project and I don't want switch to other libraries. I really appreciate this library and I want use it. 

Thanks

**Comment by marqbeniamin** [comment]
@Tropicalista done, you can use the dev branch with that feature.

**Pull request merged**
