### PR TITLE
Fix <md-file> 'badInput' of undefined #2260

### PR DESCRIPTION
**Pull request by mikimoresi**
avoid error when there is not validity prop of $el
error has open issue #2260

### CODE REVIEW

**Review by dragosct10 — APPROVED** [review]

**Review by marqbeniamin — APPROVED** [review]

**Comment by sarah-tammenga-ibis** [comment]
Hi when will this be merged?

**Comment by allanvobraun** [comment]
Merge this please!!!

**Comment by mikimoresi** [comment]
you can  clone and use my fork in the meantime, is exaactely the same but this fix and a new feature in dialogs comp.

**Comment by tyge68** [comment]
You can use https://github.com/ds300/patch-package#readme it's really cool and helping when deploying on azure static webapp :)

**Comment by robertohori-learn** [comment]
How long we will wait for it? We are having this problem more than 3 months .

**Comment by nelsonbits** [comment]
pretty please can this be merged?

**Comment by saisk73** [comment]
Can you update it in NPM package I'm using vue-material in my project and I get errors while using select inputs.

**Pull request merged**
