### PR TITLE
feat(MdTableCell): add `md-id` prop

### LINKED ISSUE #1535: [MdTable] autogenerated headers are not differentiated in any way
When using custom template table as we cannot sort otherwise headers are automatically generated with use md-label and md-sort-by.
Can we somehow add ids for them so that they can be differentiated from one another? Because frankly it causes quite a lot of problems for UI automated testing.
So it would be great if you guys either added support for md-sort-by for md-table-head or added generating of ids for custom template headers, thanks.

### PR DESCRIPTION
**Pull request by Samuell1**
Resolves #1535

### CODE REVIEW

**Comment by marcosmoura** [comment]
@Samuell1 Can you add a mention on the documentation website?

**Comment by Samuell1** [comment]
@marcosmoura yes but there are missing docs fully :D

**Comment by marcosmoura** [comment]
@Samuell1 What?

**Comment by Samuell1** [comment]
@marcosmoura i mean Api is "Coming soon..."

**Pull request merged**
