### PR TITLE
fix(MdTableRow): update selectableItem while `mdItem` changed

### LINKED ISSUE #1492: md-table's data doesn't get updated properly
### What is actually happening?

I'm trying to implement a pagination function with vue 2.5.3 / vue-material1.0.0 and the problem is whenever I update the
model , the table gets updated with the newly fetched model but the md-table component still has the previous data so when I check the "select all" box it gets the previous data only which makes the selected variable contain only the page 1 data when in fact I am in page 2. anyone have any suggestions on how to deal with this?

### PR DESCRIPTION
**Pull request by VdustR**
fix #1492

### CODE REVIEW

**Comment by ueharajohji** [comment]
Hi , guys sorry for the late updated. Will 'npm update' get this fix since it is already committed ?

**Comment by Samuell1** [comment]
No, it needs to be released @ueharajohji

**Comment by ueharajohji** [comment]
In order to use the fix ,I just need to change the file manually and rebuild , is that correct?

**Comment by Samuell1** [comment]
Yes @ueharajohji

**Comment by ueharajohji** [comment]
I'm sorry for the lack of research but I tried running the command 'npm install' to get the node modules and  'npm run -script build' to get a new build file but it shows me an error when building.

**Comment by ueharajohji** [comment]
Hello , I successfully build the file , thanks again for the fix.

**Pull request merged**
