### PR TITLE
feat(MdDatepicker): Support with field variants 

### PR DESCRIPTION
**Pull request by shafimsp**
To support with all field variants (bottom-line, box and raised)

### CODE REVIEW

**Comment by shafimsp** [comment]
@marcosmoura @Samuell1 i suggest, rename this component to 'MdDateInput' and propose new component 'MdDatepicker', this wrap any component and make it as datepicker (like MdMenu)


DOM structure:
```
 <md-datepicker v-model="selectedDate" >
      <md-button md-datepicker-trigger class="md-icon-button">
        <md-icon>event</md-icon>
      </md-button>
      <label>{{ selectedDate }}</label>
</md-datepicker>
```

if you are agree with, i will create a PR

**Comment by shafimsp** [comment]
@marcosmoura @Samuell1 i suggest, rename this component to 'MdDateInput' and propose new component 'MdDatepicker', this wrap any component and make it as datepicker (like MdMenu)


DOM structure:
```
 <md-datepicker v-model="selectedDate" >
      <md-button md-datepicker-trigger class="md-icon-button">
        <md-icon>event</md-icon>
      </md-button>
      <label>{{ selectedDate }}</label>
</md-datepicker>
```

if you are agree with, i will create a PR

**Comment by Samuell1** [comment]
@shafimsp it needs to be after your PRs are merged.

**Comment by shafimsp** [comment]
ok, thank you

@Samuell1  can you please review it.

**Comment by marcosmoura** [comment]
@shafimsp Can you fix the conflicts??

**Comment by marcosmoura** [comment]
This was canceled. Due to the new changes on Material Design guidelines, this will no longer be applied.

**Pull request closed without merging**
