### PR TITLE
feat(MdApp): add full height class

### PR DESCRIPTION
**Pull request by Samuell1**
https://github.com/vuematerial/vue-material/issues/1222, https://github.com/vuematerial/vue-material/issues/1250

### CODE REVIEW

**Comment by VdustR** [comment]
I think give it `100%` and let them decide the height from outer is more flexible in my opinion.

In some case someone might stick an ad on top or the bottom, or spit the screen up and down for another subpage.

**Comment by marcosmoura** [comment]
I like both proposals. I think this should only come when we have the boilerplates.

**Comment by Samuell1** [comment]
It would be better to add prop like `md-height` and default will be `100vh` ? @VdustR @marcosmoura

**Comment by VdustR** [comment]
How about custom classes and style allowed?

https://github.com/VdustR/vue-material/commit/2a9fa0e2adf0560c13c8fde3d7dba284b0a8f933

**Comment by marcosmoura** [comment]
@VdustR I liked it!

**Pull request closed without merging**
