### PR TITLE
Added Onboarding component

### PR DESCRIPTION
**Pull request by fergardi**
Hello again!

Based on the Tabs component, I developed a simple Onboarding (simple carousell actually) component.

image

image

image

Whis some custom css now I can do some epic landing pages like this in my cordova app:

13363c03-bfec-4c1a-b509-4b4c62dbc728

What do you think?

### CODE REVIEW

**Comment by fergardi** [comment]
Now with swipeable event handlers thanks to #429 code!

**Comment by marcosmoura** [comment]
Great PR! I'm just hold this up to merge later.
Thank you SO MUCH!

**Comment by fortil** [comment]
when will be ready? 
:D

**Comment by bitencode** [comment]
looks nice - I don't understand the "Onboarding" - you said it's a carousel, it looks like a carousel, why not just call it `md-carousel`, I think there is a much better chance people will find it by that name.
https://en.wikipedia.org/wiki/Onboarding

**Comment by Samuell1** [comment]
@bitencode in official docs its called onboarding https://material.io/guidelines/growth-communications/onboarding.html#onboarding-top-user-benefits

**Comment by bitencode** [comment]
@Samuell1 Actually what they appear to be outlining there is the process of "on-boarding" your customers in using your app (making it friendly, how to do things, etc...).  That is more clear if you read the whole "On-Boarding" section from the top.  In the "top user benefits" outline they refer to this component as an "auto-rotating carousel" 😉 
onboarding_-_growth___communications_-_material_design_guidelines

**Comment by peey** [comment]
This PR's status is that it's merged but it seems that the code has disappeared from the codebase altogether.

What's the correct way to have a carousel / onboarding element in the latest versions?

**Comment by Samuell1** [comment]
@peey Hey, its because this was merged in older version of vue-material. (https://vue-material-old.netlify.com/)

**Comment by peey** [comment]
Alright. I think you should open up a corresponding issue if you plan to add it as a component / want someone to add it as a component. For the time being I'm planning to use third-party components like https://github.com/antoniandre/vueper-slides for my use case

**Pull request merged**
