### PR TITLE
fix(MdField): fix textarea and inline issues

### PR DESCRIPTION
**Pull request by shafimsp**
Fix issues caused by #1600
Fix issues mentioned in #1601 [comment](https://github.com/vuematerial/vue-material/pull/1601#issuecomment-376649139)
Fix prefix and suffix with icon and other variants issues

### CODE REVIEW

**Comment by shafimsp** [comment]
@marcosmoura can you please review and merge asap, so i can do some this related fix in other field components (chips, file autocomplete and datepicker)

**Comment by Samuell1** [comment]
Looks like label for textarea with grow is still misaligned 

obrazok

**Comment by shafimsp** [comment]
Sorry, i didn't get you..

**Comment by Samuell1** [comment]
@shafimsp space under label is bigger then on normal inputs

**Comment by shafimsp** [comment]
@Samuell1 I have looked, i think its correct.

Please see below images.
- https://material-components-web.appspot.com/text-field.html
screenshot-material-components-web appspot com-2018 03 30-11-42-18

- Normal Text field 
screenshot-localhost-8080-2018 03 30-11-41-47
- Textarea with autogrow
screenshot-localhost-8080-2018 03 30-11-40-57

**Comment by Samuell1** [comment]
I overlayped normal input with textarea autogrow input and label is misaligned. Screenshot is from Firefox maybe thats the issue?
obrazok

**Comment by shafimsp** [comment]
I was checked on chome. Will look on Firefox

**Comment by shafimsp** [comment]
@Samuell1 can you please check it? Thank you

**Comment by Samuell1** [comment]
Now it looks fine.

obrazok

**Pull request merged**
