### PR TITLE
Tabs navigation arrows

### PR DESCRIPTION
**Pull request by igor-ribeiro**
#430

### CODE REVIEW

**Comment by marcosmoura** [comment]
@igor-ribeiro Can you sync your branch with the latest develop?

**Comment by marcosmoura** [comment]
@igor-ribeiro ping

**Comment by igor-ribeiro** [comment]
@marcosmoura Done

**Comment by marcosmoura** [comment]
I think that would be great to have a prop to disable the navigation buttons. Maybe a `md-pagination` that have `true` as default. 
What do you think?

**Comment by igor-ribeiro** [comment]
@marcosmoura `md-navigation`, maybe?

**Comment by marcosmoura** [comment]
Yes! Better!

**Comment by marcosmoura** [comment]
Hi @igor-ribeiro. Would you mind to send me your personal email?

**Comment by marcosmoura** [comment]
Hi @igor-ribeiro 
I know that there is a long time since you developed this great PR. Can you please fix the conflicts? Just awaiting this to merge!

**Pull request merged**
