### PR TITLE
fix: z-index issues

### PR DESCRIPTION
**Pull request by Samuell1**
Components issues: #1157, #1190, #1149

And docs issue #1134

### CODE REVIEW

**Comment by alexmedkex** [comment]
I have the latest version installed and I still have this issue

**Comment by Samuell1** [comment]
@alexmedkex because builded version is something changing and then this fix doesnt work :/ https://github.com/vuematerial/vue-material/pull/1525#issuecomment-369331004

**Comment by alexmedkex** [comment]
Is there any workaround at this moment?

**Comment by Samuell1** [comment]
@alexmedkex just apply same css to rewrite z-indexes

**Comment by alexmedkex** [comment]
I tried but it didn't work for me. I wasn't exactly sure which tag that I
should modify the z-index of, but I tried on everything but no success.

**Comment by Samuell1** [comment]
@alexmedkex use important that should help

**Comment by alexmedkex** [comment]
<md-dialog class="dialog" :md-active.sync="showDialog">
<md-dialog-title>Make Order</md-dialog-title>
<md-field md-select-menu-container>
<label for="Outcome Token">Outcome Token</label>
<md-select v-model="outcomeAddress" name="Outcome token">
<md-option v-for="outcome in outcomes" :key="outcome.address" :value="
outcome.address">{{ outcome.name }}</md-option>
</md-select>
</md-field>
<md-button class="md-raised md-primary" @click="setAllowance()">Set
Allowance</md-button>
</md-dialog>

Where should I modify the CSS? I'm trying with

z-index: 99999 !important;

but I can't get it to work

**Comment by Samuell1** [comment]
on what class do you puting it? @alexmedkex

**Comment by alexmedkex** [comment]
I tried on different tags/classes, like this for example:

<md-dialog class="dialog" :md-active.sync="showDialog">
            <md-dialog-title>Make Order</md-dialog-title>
            <md-field>
                <label for="Outcome Token">Outcome Token</label>
                <md-select class="md-select-menu-container" v-model="outcomeAddress" name="Outcome token">
                    <md-option v-for="outcome in outcomes" :key="outcome.address" :value="outcome.address">{{ outcome.name }}</md-option>
                </md-select>
            </md-field>
             <md-button class="md-raised md-primary" @click="setAllowance()">Set Allowance</md-button>
        </md-dialog>
         <md-button class="md-raised md-primary" @click="showDialog = true">Set Allowance</md-button>

.md-select-menu-container {
           z-index: 99999 !important;
}

**Comment by alexmedkex** [comment]
I tried on different tags/classes, for example like this:

<md-dialog class="dialog" :md-active.sync="showDialog">
<md-dialog-title>Make Order</md-dialog-title>
<md-field>
<label for="Outcome Token">Outcome Token</label>
<md-select class="md-select-menu-container" v-model="outcomeAddress"
name="Outcome
token">
<md-option v-for="outcome in outcomes" :key="outcome.address" :value="
outcome.address">{{ outcome.name }}</md-option>
</md-select>
</md-field>
<md-button class="md-raised md-primary" @click="setAllowance()">Set
Allowance</md-button>
</md-dialog>


.md-select-menu-container {
z-index: 99999 !important;
}

**Comment by Samuell1** [comment]
@alexmedkex try class `md-menu-content`

**Comment by alexmedkex** [comment]
Yes it works! Thank you!

**Pull request merged**
