### PR TITLE
Fix for bug that allowed disabled options in Select component to be selected

### PR DESCRIPTION
**Pull request by praneetloke**
Fix for #529. Updated docs with an example of disabled items in the Select component.

### CODE REVIEW

**Comment by praneetloke** [comment]
@marcosmoura just realized that the contributing guide says not to open PRs against the master branch. Does that apply for bug fixes too or just for features? Let me know if you would like me to close this and open a new one against the develop branch instead. It's not a problem for me.

**Comment by marcosmoura** [comment]
It seems that you're branch are outdated. Can you sync your fork?

**Comment by praneetloke** [comment]
@marcosmoura should I close and re-open this PR against the `develop` branch because I worked off the `master` branch when I made the fix.

**Comment by praneetloke** [comment]
@marcosmoura ping.

**Comment by marcosmoura** [comment]
@praneetloke Could you rebase your branch?

**Comment by praneetloke** [comment]
@marcosmoura I'll open a new PR from my fork's develop branch.

**Pull request closed without merging**
