### PR TITLE
nl_BE translation should be good enough for nl_NL aswell.

### PR DESCRIPTION
**Pull request by maarteNNNN**

### CODE REVIEW

**Comment by maarteNNNN** [comment]
They're not finished yet. Need to do some refining. The first commit is discarded, I'm still struggling with how to use git properly. I made another pull request for that #1638

**Comment by marcosmoura** [comment]
@maarteNNNN First of all, thank you so much for starting this branch!
I don't know any about Dutch. This translation works for the Netherlands as well? What's the main difference?

**Comment by maarteNNNN** [comment]
@marcosmoura They're basically the same. They have few words that have a different meaning. Mostly used in dialects. It's not as huge of difference compared Portuguese from Portugal and Brazil
And check your mail marcosvmmoura@gmail.com, I sent you an email ;)

**Comment by maarteNNNN** [comment]
This should be production ready, might be some flaws. There's only two sentences I have difficulty putting into words. Maybe someone else of the community can help.

**Pull request closed without merging**
