### PR TITLE
feat(MdAutocomplete) Field variant support changes

### PR DESCRIPTION
**Pull request by shafimsp**
Note: Please merge just after #1545

### CODE REVIEW

**Comment by marcosmoura** [comment]
@shafimsp Can you fix the conflicts?

**Comment by shafimsp** [comment]
conflicts fixed

**Comment by marcosmoura** [comment]
@shafimsp This PR can't be approved! There are too many removals that will break the code entirely.
It would be safer if you could be redone this PR... What do you think?

**Comment by marcosmoura** [comment]
This was cancelled. Due to the new changes on Material Design guidelines this will no longer be applied.

**Pull request closed without merging**
