### PR TITLE
feat(MdFile) Support for field variants

### PR DESCRIPTION
**Pull request by shafimsp**
This PR is to support MdFile with MdField and its variants

### CODE REVIEW

**Comment by marcosmoura** [comment]
@shafimsp Can you fix the conflicts?

**Comment by shafimsp** [comment]
@marcosmoura  conflicts fixed

**Comment by shafimsp** [comment]
@marcosmoura i need to merge PR #1601 before resolve these conflicts. its related.

**Comment by shafimsp** [comment]
im closing this PR, i have created another PR #1662

**Pull request closed without merging**
