### PR TITLE
Add ability to use icon for select component.

### PR DESCRIPTION
**Pull request by pml984**
Add ability to use icon for select. Also provide a new md-menu-options prop to pass options to menu within select.

### CODE REVIEW

**Comment by Morgul** [comment]
@pml984 can you please rebase this? I'd like to see it get in for the next release, if possible.

**Comment by pml984** [comment]
I'll take care of that today

**Comment by pml984** [comment]
Sorry for the delay, I rebased and pushed back up.

**Comment by pablohpsilva** [comment]
Awesome work @pml984 !
Thank you :D

**Pull request merged**
