### PR TITLE
md-autocomplete component

### PR DESCRIPTION
**Pull request by pablohpsilva**
After a while I had to create this component from the ground up.

Please, feel free to take a look in the code and help me out.

### Usage example: 

```html
<md-input-container>
  <md-autocomplete
    :fetch="customFetchFunction"
    print-attribute="name"
    query-param="q"
    :debounce="1000"
    :minChars="3"
    v-model="object.name"
    @selected="setSelectedElement"/>
</md-input-container>
```

Or even with no `fetch` at all:

```html
<md-input-container>
  <md-autocomplete
    :list="[{name: 'oi'}, {name: 'hi'}, {name: 'salut'}]",
    :filter-list="filterFunction"
    print-attribute="name"
    :debounce="5E2"
    :minChars="1"
    v-model="object.name"
    @selected="setSelectedElement"/>
</md-input-container>
```

### Example

mar-27-2017 14-35-29

The only requirement in this component is to have a `Vue.**$http**` variable available when NOT using the `:fetch` prop.

Soon I'll make another PR for a Chips + Autocomplete component.
Cheers.

### CODE REVIEW

**Comment by Samuell1** [comment]
Nice! I think component can not be dependent on other dependencies, that fetching from server with vue-resource (i using graphql for example), i think best way is send array of items from parent where is fetching.

**Comment by pablohpsilva** [comment]
@Samuell1 I could remove that dependency for good. The parent will have to send a function. The mdAutocomplete will execute the function and extract the information.

What do you think?

**Comment by Samuell1** [comment]
@pablohpsilva yes that will be good, but parent component run fetch and with data you send array of items to mdAutocomplete

**Comment by pablohpsilva** [comment]
OK, no problem. Do you think it would be a good idea to give both options (array of items OR a fetch function) or just one?

**Comment by Samuell1** [comment]
@pablohpsilva for me is better array of items

**Comment by Morgul** [comment]
(I apologize if I'm suggesting what @Samuell1 already suggested, but I didn't entirely follow the discussion.)

@pablohpsilva I'd suggest supporting two APIs, either a prop (array) or  a fetch function that the autocomplete component executes. (Rereading, I think that _is_ what @Samuell1 was suggesting.)

What this will allow for (that I find interesting, and very useful) is use of autocomplete as a 'combobox' style control; in essence a editable select. We'll be getting two controls for the price of one, basically.

**Comment by pablohpsilva** [comment]
@Morgul yeap... That's what I understood too LOL.
I should soon push the code and make this bad boy work.

Thank you guys! :)

P.S.: In my opinion, using a fetch function is way cooler. It makes the component really powerful :D

**Comment by pablohpsilva** [comment]
Done @Morgul and @Samuell1 .
Examples:

```html
<md-input-container>
  <md-autocomplete
    :fetch="customFetchFunction"
    print-attribute="name"
    query-param="q"
    :debounce="1000"
    :minChars="3"
    v-model="object.name"
    @selected="setSelectedElement"/>
</md-input-container>
```

Or even with no `fetch` at all:

```html
<md-input-container>
  <md-autocomplete
    :list="[{name: 'oi'}, {name: 'hi'}, {name: 'salut'}]",
    :filter-list="filterFunction"
    print-attribute="name"
    :debounce="5E2"
    :minChars="1"
    v-model="object.name"
    @selected="setSelectedElement"/>
</md-input-container>
```

**Comment by matthewpull** [comment]
@pablohpsilva Out of interest, why would you need a debounce duration if the list is provided? Surely the debounce is just applying to calls to the fetch function. If there is no fetch function then this is superfluous, no?

**Comment by pablohpsilva** [comment]
That's true, @matthewpull , but I'm using it to avoid calling the filterFunction. I'll let the user type and debounce it until he's done before calling once the filter on the `list`.

That's why I kept it.

**Comment by matthewpull** [comment]
@pablohpsilva Ah I see, that makes sense. Looks like a great component!

**Comment by asadhshujau** [comment]
hope this has option to add new tags
like when a non existing tag is typed an event is fired and we can do what we want by taking an action for that event

**Comment by pablohpsilva** [comment]
@asadhshujau you mean the chips autocomplete? If you do, this is not the PR for it. This pull request concerns only the autocomplete component. 

Rest assured I'll add that once I finish the chips autocomplete component :D

**Comment by asadhshujau** [comment]
@pablohpsilva ahah yeah 
thanks for replying though :D

**Comment by pablohpsilva** [comment]
@asadhshujau @Samuell1 I'm almost done with the mdChipsAutocomplete component. All I need is to test it a lil more and **have the mdAutocomplete PR accepted** (Please, @marcosmoura , help us out here LOL).

🚀 🚀 🚀 🚀 🚀

**Comment by buccfer** [comment]
@pablohpsilva I tried merging this PR in my vue-material fork. I run `npm run dev` and checked the autocomplete you added in the docs. When I type one character the autocomplete retrieves the results and after some seconds the dropdown closes, so I'm not able to select anything. Is that possible?

Thanks!

**Comment by pablohpsilva** [comment]
Hello @buccfer !
I'm not sure what happened there... But I can take a look at it ASAP.

**Comment by pablohpsilva** [comment]
I tested again and I couldn't find the issue nor get the error you had.

My steps were:
1. git pull the autocomplete branch;
2. yarn && yarn dev;
3. open the Input page and typed "pablohp" in the autocomplete;
4. waited a second until the list popped up;
5. waited a few seconds to see if it closes;
6. selected one of the results and checked the console for errors.

**Comment by buccfer** [comment]
@pablohpsilva  My steps were:

1. git clone git@github.com:pablohpsilva/vue-material.git
2. cd vue-material
3. npm install  -> Throws error: npm ERR! notarget No compatible version found: extract-text-webpack-plugin@beta.

Maybe I am doing something wrong, because I can't even run the dev server in the autocomplete branch.

**Comment by d3radicated** [comment]
Any news for merging this component?

**Comment by Morgul** [comment]
@pablohpsilva I feel this is ready to merge. Do you?

**Comment by pablohpsilva** [comment]
@Morgul I'll test the component once again right now. @buccfer got some issues that I'll have to check.

@buccfer I'm using yarn instead of NPM. Maybe that's why I didn't get any of those errors.

@d3radicated Soooon!!! I hope LOL :D

**Comment by pablohpsilva** [comment]
@buccfer Yeap! Now I see the same erros you saw.
This PR was based on an old branch. Those files (mdSpinner, package.json, etc) will not be modified once this PR is accepted. They were corrected on the current `develop` branch.
Dude, I'm sorry for taking too long to see what's up with this. It won't happen again.

@Morgul and @d3radicated I think this PR can be accepted now.

**Comment by buccfer** [comment]
@pablohpsilva @marcosmoura Nice to see this has been merged. Anyway, I don't see the docs updated. Can you please deploy it? 

Best :).

**Comment by d3radicated** [comment]
@buccfer, it will be eventually merged to `master` branch once issues are fixed. You can follow PR #767. 😃

**Comment by buccfer** [comment]
@d3radicated I see "pablohpsilva  merged 21 commits into vuematerial:master from pablohpsilva:autocomplete".. that's why I thought it was ready..

**Comment by Samuell1** [comment]
@buccfer but they need to recompile it, after they add new things :)

**Comment by pablohpsilva** [comment]
@buccfer We're working as much as we can to give you guys lots of bug fixes and new features. 
I promise: from now on, we'll have consistent and frequent releases.
@Samuell1 @d3radicated @buccfer you guys rock! Thank you!

P.S.: Wait. Awesome things are coming.

**Comment by dannynpham** [comment]
@pablohpsilva Hey I have the latest version of vue material and I followed your instructions here, but I can't get md-autocomplete to work. All the other components work normally for me.

**Comment by pablohpsilva** [comment]
Really @dannynpham ? :(

Could you please provide an example here so I can test it? The code is not yet on master, so... I will test it manually :)

**Comment by dannynpham** [comment]
@pablohpsilva Ah that makes sense why I'm getting md-autocomplete not registered. I saw this pull request getting merged in so I thought I can use it. How would I get this to work? I'm not really able to follow your examples at the top what does each of the options do? Thanks again for helping me I really appreciate it.

**Comment by luizcaciatori** [comment]
@dannynpham  you got use this component? 
@pablohpsilva why this component is not presented in documentation?

**Comment by dannynpham** [comment]
@luizcaciatori Yea it works great, I actually forked it so that I could use the up and down arrow for selection. [http://vuematerial.io/#/components/input](Here's the docs for it.)

**Comment by zeinware** [comment]
is there any method to change offset, and menu size?

**Pull request merged**
