### PR TITLE
Added Stepper component

### PR DESCRIPTION
**Pull request by fergardi**
Hello.

As promised, I sunk into your code and created a simple but cool (haha) component: Stepper.

I know it is far away from Google's Material Design Stepper specifications, lacking live edition, scrolling, automatic enabled/disabled states, etc. But wanted to collaborate and learn, so here it is, improvements needed of course. It uses custom componentes, scss, theme, and simple props. What do you think?

image

Cheers.

### CODE REVIEW

**Comment by marcosmoura** [comment]
Hi @fergardi 
Thank you SO MUCH for this PR. I will run your code to see and I get back to you, ok?

**Comment by marcosmoura** [comment]
I liked the idea and the css behind it. I will use as the codebase to develop the Stepper with all the functionalities in the near future. If you want to develop the missing features here, I would love to discuss about :D

**Comment by fergardi** [comment]
GI'm glad you liked it. I'm more a designer-type of guy so I'll leave the js magic to you if you dont mind :P. Meanwhile I think I'll focus on the Grid css problems of #485.

**Comment by marcosmoura** [comment]
Thank you so much!

**Comment by rzb** [comment]
@marcosmoura When do you plan to release the stepper component? I need it so badly. I'd love to help you if I hadn't just jumped into Vue a couple days ago.

**Comment by abotsi** [comment]
Hi,
Nice library, and nice PR! I'm also looking for the stepper component, could you give some status update? I'm ready to help if you need to :)
Thanks @fergardi & @marcosmoura for your work!

**Comment by Morgul** [comment]
@fergardi #717 appears to be a more complete implementation. I would love to get your thoughts (as the original author of the proposed component) on that PR.

**Comment by vin-e** [comment]
@fergardi and @Morgul, I would definitely like hear your thoughts and I am ready to update it as needed. I used this pull request as a base but diverted a bit to match the google material spec.

**Comment by pablohpsilva** [comment]
I'll close this PR since @vin-e enhanced this code base. Thank you @fergardi for your awesome work!
And thank you @vin-e for making it more Material Design like.

**Pull request closed without merging**
