### PR TITLE
weird asterisks in IE

### PR DESCRIPTION
**Pull request by VisualBean**
from
image
to
image

### CODE REVIEW

**Comment by argarak** [comment]
Hi @VisualBean, thanks for contributing. However, in the [Vue Material Guide](https://github.com/vuematerial/vue-material/blob/master/.github/CONTRIBUTING.md) it states that you must work in a `develop` or `develop`-derived branch in your own fork, *this means that you commit to `develop` and not `master`*. Could you please make a new PR and commit your changes to `develop`?

**Comment by VisualBean** [comment]
Ofcourse - i thoughr i already had :)

**Comment by argarak** [comment]
@VisualBean, sorry if I got my wording wrong there, what I meant was that you need to modify develop and not master. What you've done here is modified master (changed a file on Github in the wrong tree), are committing the changes made to `master` (this is the reason for extra commits in your PR) and then are pushing these changes to `develop`. You have correctly set the branch where the PR will be merged (`develop`), however you cannot commit the changes made from `master` to `develop`.

I hope this clears it up.

**Comment by VisualBean** [comment]
Ad i said i thought i was on develop.. ill fix it at some point tomorrow just reject the pr and ill create a new one

**Comment by argarak** [comment]
You'll have to close the PR, as I'm not a collaborator, I don't have write access.

**Pull request closed without merging**
