### PR TITLE
Fix theme bug in issue #906

### PR DESCRIPTION
**Pull request by twojustin**
see issue #906

### CODE REVIEW

**Comment by pablohpsilva** [comment]
Thank you @twojustin !! You rock!! :D

**Comment by pablohpsilva** [comment]
Could you please make the PR point to `develop` branch?

**Comment by pablohpsilva** [comment]
Something went wrong with your PR. It says you changed 139 files. Could you check it out please?

**Comment by twojustin** [comment]
i've opened a new one in #999

**Pull request closed without merging**
