### PR TITLE
feat(MdTable): pagination

### PR DESCRIPTION
**Pull request by fabioviana**
# Examples:

**Pagination by memory:**
```
<template>
  <md-table class="table" :value.sync="paginatedData" md-sort="userName" md-sort-order="asc">
    <md-table-row slot="md-table-row" slot-scope="{ item }">
      <md-table-cell md-label="UUID" md-sort-by="uuid">{{ item.uuid }}</md-table-cell>
      <md-table-cell md-label="User Name" md-sort-by="userName">{{ item.userName }}</md-table-cell>
    </md-table-row>
    <md-table-pagination :md-data.sync="data" :md-paginated-data.sync="paginatedData" :md-page-size="5">
    </md-table-pagination>
  </md-table>
</template>

<script lang="babel">
export default {
  name: 'Example',
  data: () => ({
    data: [],
    paginatedData: []
  }),
  created () {
    this.load()
  },
  methods: {
    load () {
      this.data = [
        {
          uuid: 1,
          userName: 'test 1'
        },
        {
          uuid: 2,
          userName: 'test 2'
        },
        {
          uuid: 3,
          userName: 'test 3'
        },
        {
          uuid: 4,
          userName: 'test 4'
        },
        {
          uuid: 5,
          userName: 'test 5'
        },
        {
          uuid: 6,
          userName: 'test 6'
        }
      ]
    }
  }
}
</script>

<style lang="scss" scoped>
</style>
```

**Pagination by API REST:**
```
<template>
  <md-table class="table" :value.sync="paginatedData" md-sort="userName" md-sort-order="asc" :md-sort-fn="sort">
    <md-table-row slot="md-table-row" slot-scope="{ item }">
      <md-table-cell md-label="UUID" md-sort-by="uuid">{{ item.uuid }}</md-table-cell>
      <md-table-cell md-label="User Name" md-sort-by="userName">{{ item.userName }}</md-table-cell>
    </md-table-row>
    <md-table-pagination :md-data.sync="data" :md-paginated-data.sync="paginatedData" :md-page-size="5" :md-update="updatePage">
    </md-table-pagination>
  </md-table>
</template>

<script lang="babel">
import http from 'axios'

export default {
  name: 'Example',
  data: () => ({
    data: {},
    paginatedData: []
  }),
  created () {
    this.load()
  },
  methods: {
    load () {
      this.updatePage(1, 5, 'userName', 'asc')
    },
    async updatePage (page, pageSize, sortBy, sortOrder) {
      // it will called when: page change, sort change and pageSize change
      var data = (await http.get(YOUR_URL, {page, pageSize, sortBy, sortOrder})).data
      this.data = {
        mdData: data.resultList, // array with the currently page data, it returned by API
        mdCount: data.count // total row count
      }
    }
  }
}
</script>

<style lang="scss" scoped>
</style>
```

### CODE REVIEW

**Comment by Samuell1** [comment]
Looks nice! But does this work without sending data to pagination? like calling page, size on your api?

And script content should be indented with 2 spaces

**Comment by fabioviana** [comment]
When you use pagination by API, you need to registry the property md-update. It is a function that receive the page, page size, field to sort and orientation sort. Your API can be anyway, since it returns the paginated data and the total of elements (disregarding pages).

About the indent, I fixed and pushed right now.

**Comment by marcosmoura** [comment]
@fabioviana Why do we need "data" and "paginatedData"? There is a way that you can think that we could use the same value from `:value`?

**Comment by fabioviana** [comment]
Because it's necessary to preserve the original date. When the data is paginated by memory the md-table uses the: value to render and the md-table-pagination needs to store the original date to paginate to next / previously page or sort it. So, they cannot be equals. Maybe we can use this.MdTable.emitEvent('input', mdPaginatedData) from md-table-pagination. I didn't try yet.

When the data is paginated by API the prop md-data of md-table-pagination needs to be a object, containing mdData and mdCount.

**Comment by 597796340** [comment]
@fabioviana It doesn't work, when i follow your demo: Pagination by API REST. 
It just show the table without pagination. I don't know what error. Please help me, thx!
```vue
<template>
  <md-table class="table" :value.sync="paginatedData" md-sort="userName" md-sort-order="asc">
    <md-table-row slot="md-table-row" slot-scope="{ item }">
      <md-table-cell md-label="UUID" md-sort-by="uuid">{{ item.uuid }}</md-table-cell>
      <md-table-cell md-label="User Name" md-sort-by="userName">{{ item.userName }}</md-table-cell>
    </md-table-row>
    <md-table-pagination :md-data.sync="data" :md-paginated-data.sync="paginatedData" :md-page-size="5"></md-table-pagination>
  </md-table>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import MdTablePagination from "../components/MdTable/MdTablePagination.vue";
import MdTable from "../components/MdTable/MdTable.vue";

@Component({
  components: {
    MdTable,
    MdTablePagination
  }
})
export default class Test extends Vue {
  data = {};
  paginatedData = [];

  created() {
    this.load();
  }

  load() {
    this.updatePage(1, 5, "userName", "asc");
  }

  updatePage(page, pageSize, sortBy, sortOrder) {
    // it will called when: page change, sort change and pageSize change
    const data = [
      {
        uuid: 1,
        userName: "test 1"
      },
      {
        uuid: 2,
        userName: "test 2"
      },
      {
        uuid: 3,
        userName: "test 3"
      },
      {
        uuid: 4,
        userName: "test 4"
      },
      {
        uuid: 5,
        userName: "test 5"
      },
      {
        uuid: 6,
        userName: "test 6"
      }
    ];
    this.data = {
      mdData: data, // array with the currently page data, it returned by API
      mdCount: 6 // total row count
    };
  }
}
</script>

**Comment by 597796340** [comment]
Working now !!! I download source code of the dev branch and rewrite the component of MdTable.vue and MdTablePagination.vue ,also change the demo of : Pagination by API REST
`MdTable.vue : `
```
<slot v-if="!hasValue && $scopedSlots['md-table-row']" />
```
change to 
```
<slot v-if="!hasValue && $scopedSlots['md-table-pagination']" />
```

`MdTablePagiantion.vue: `
```
<template>
  <div class="md-table-pagination">
    <template v-if="mdPageOptions !== false">
      <span class="md-table-pagination-label">{{ mdLabel }}</span>

      <md-field>
        <md-select v-model="currentPageSize" md-dense md-class="md-pagination-select">
          <md-option v-for="amount in mdPageOptions" :key="amount" :value="amount">{{ amount }}</md-option>
        </md-select>
      </md-field>
    </template>

    <span>{{ mdPage }}/{{ pageCount }}</span>

    <md-button class="md-icon-button md-table-pagination-previous" @click="goToPrevious()" :disabled="mdPage === 1">
      <md-icon>keyboard_arrow_left</md-icon>
    </md-button>

    <md-button class="md-icon-button md-table-pagination-next" @click="goToNext()" :disabled="mdPage === pageCount">
      <md-icon>keyboard_arrow_right</md-icon>
    </md-button>
  </div>
</template>
<script lang="babel">
/* tslint:disable */
  const getPageData = (data, mdPage, mdPageSize) => {
    return data.slice((mdPage - 1) * mdPageSize, ((mdPage - 1) * mdPageSize) + mdPageSize)
  }
  export default {
    name: 'MdTablePagination',
    inject: ['MdTable'],
    props: {
      mdData: {
        type: [Array, Object]
      },
      mdPageOptions: {
        type: [Array, Boolean],
        default: () => [5, 10, 25, 50, 100]
      },
      mdPaginatedData: {
        type: Array,
        default: () => []
      },
      mdPageSize: {
        type: Number,
        default: 10
      },
      mdUpdate: {
        type: Function
      },
      mdLabel: {
        type: String,
        default: '每页显示:'
      }
    },
    data: () => ({
      mdPage: 0,
      mdCount: 0,
      currentPageSize: 0
    }),
    computed: {
      pageCount () {
        return this.getPageCount()
      }
    },
    created () {
      // overhide MdTable.sortTable to call pagination sort
      this.MdTable.sortTable = this.sort
    },
    watch: {
      mdData: {
        immediate: true,
        handler (mdData) {
          this.mdData = mdData
          this.updatePage()
        }
      },
      mdPageSize: {
        immediate: true,
        handler (pageSize) {
          this.currentPageSize = pageSize
          this.updatePage()
        }
      },
      currentPageSize: {
        immediate: true,
        handler (newValue, oldValue) {
          if (oldValue) {
            if (this.mdData && this.mdData.mdData) {
              // external pagination
              this.mdUpdate(this.mdPage, this.currentPageSize, this.MdTable.sort, this.MdTable.sortOrder)
            } else {
              // internal pagination
              this.updatePage()
            }
          }
        }
      }
    },
    methods: {
      getPageCount () {
            debugger
        if (this.mdCount % this.currentPageSize) {
          return Math.floor((this.mdCount / this.currentPageSize)) + 1
        } else {
          return Math.floor((this.mdCount / this.currentPageSize))
        }
      },
      setPage (mdPage, mdCount) {
            debugger
        this.mdPage = mdCount > 0 ? (mdPage > 0 ? mdPage : (this.mdPage > 0 ? this.mdPage : 1)) : 0
        var pageCount = this.getPageCount()
        if (this.mdPage > pageCount) {
          this.mdPage = pageCount
        }
      },
      updatePage () {
        if (this.currentPageSize !== 0) {
          if (this.mdData && !this.mdData.mdData) {
            // internal pagination
            this.mdCount = this.mdData.length
            this.setPage(this.mdPage, this.mdData.length)
            if (this.mdPage > 0) {
              this.$emit('update:mdPaginatedData', getPageData(this.mdData, this.mdPage, this.currentPageSize))
            } else {
              this.$emit('update:mdPaginatedData', [])
            }
          } else if (this.mdData) {
            console.log(this.mdData);
            // external pagination
            this.mdCount = this.mdData.mdCount
            this.setPage(this.mdData.mdPage, this.mdCount)
            this.$emit('update:mdPaginatedData', this.mdData.mdData)
          } else {
            this.mdCount = 0
            this.mdPage = 0
          }
        }
      },
      goToPrevious () {
        if (this.mdData && this.mdData.mdData) {
          // external pagination/sort
          if (this.mdUpdate(this.mdPage - 1, this.currentPageSize, this.MdTable.sort, this.MdTable.sortOrder) !== false) {
            this.mdPage = this.mdPage - 1
          }
        } else {
          // internal pagination/sort
          this.mdPage = this.mdPage - 1
          this.$emit('update:mdPaginatedData', getPageData(this.mdData, this.mdPage, this.currentPageSize))
        }
      },
      goToNext () {
        if (this.mdData && this.mdData.mdData) {
          // external pagination/sort
          if (this.mdUpdate(this.mdPage + 1, this.currentPageSize, this.MdTable.sort, this.MdTable.sortOrder) !== false) {
            this.mdPage = this.mdPage + 1
          }
        } else {
          // internal pagination/sort
          this.mdPage = this.mdPage + 1
          this.$emit('update:mdPaginatedData', getPageData(this.mdData, this.mdPage, this.currentPageSize))
        }
      },
      sort () {
        if (this.mdData && this.mdData.mdData) {
          // external pagination/sort
          this.mdUpdate(this.mdPage, this.currentPageSize, this.MdTable.sort, this.MdTable.sortOrder)
        } else {
          // internal pagination/sort
          var data = this.MdTable.mdSortFn(this.mdData)
          this.$emit('update:mdData', data)
          this.$emit('update:mdPaginatedData', getPageData(data, this.mdPage, this.currentPageSize))
        }
      }
    }
  }
</script>
```

In demo of vue file, must be add `slot="md-table-pagination"` in `<md-tabel-pagination>`.
For excemple:
```
 <md-table-pagination slot="md-table-pagination" :md-data.sync="data" :md-paginated-data.sync="paginatedData" :md-page-size="2" :mdUpdate="updatePage"></md-table-pagination>
```

@fabioviana Thank you very much!!!

**Comment by sneko** [comment]
Hi! Any news on this please :) ?

**Comment by oliver-ni** [comment]
Closing in favor of #2004

**Pull request closed without merging**
