### PR TITLE
feat(MdField) Field Variants

### PR DESCRIPTION
**Pull request by shafimsp**
### Field Variants:

- Bottom Line (with Floating Label)

- Box (with Floating Label)

- Raised (Inline Only)

### Supported Components (Use inside MdField):

- MdInput

- MdFile

- MdAutocomplete

- MdChips

- MdDateInput (refactor from MdDatepicker)

### New Component:

- MdDatepicker: any element can use can as datepicker like MdMenu

### Refactored Components:

- MdFile

- MdAutocomplete

- MdChips: Now chips supported disabled option

- MdDatepicker: Renamed to MdDateInput, Can use like as date input with disabled, readonly, placeholder 

docs also updated.

### CODE REVIEW

**Comment by Samuell1** [comment]
Can you resolve conflicts? @shafimsp

**Comment by shafimsp** [comment]
Ya sure

**Comment by marcosmoura** [comment]
@shafimsp I appreciate all the changes on this PR, but it's too cluttered. There is a lot of individual changes in one single PR. It'll be too hard to test for errors and to show on changelogs.
It also introduces some breaking changes without notices, like the new markup of autocomplete, which makes old code to simply breaks.

Can you create a single PR for each subject?

You can freely choose the topics, but I would like to propose the following scenarion:

- MdField variations
- MdDatepicker changes
- MdAutocomplete changes
- MdFile changes
- MdChips changes

Can you do that?

Thank you so freaking much!

**Comment by shafimsp** [comment]
These changes are dependable thats why i have done in one PR. Only datepicker is the odd one from these..

**Comment by shafimsp** [comment]
No problem, i can create single PR for each

**Pull request closed without merging**
