### PR TITLE
fix(MdField): fix padding issues

### PR DESCRIPTION
**Pull request by Samuell1**
Fixed issues caused by #1600

### CODE REVIEW

**Comment by marcosmoura** [comment]
@Samuell1 The autogrow textarea is still misaligned

**Comment by shafimsp** [comment]
I will take of it.. 
And also have some corrections on other field components

Ok?

**Comment by marcosmoura** [comment]
@shafimsp I can't. It should be fixed now.
The other branches will need to be fixed as well.

**Comment by shafimsp** [comment]
@marcosmoura ok, so may i merge this branch with branch which i work on?

**Pull request closed without merging**
