### PR TITLE
feat(MdField) Field Variants

### PR DESCRIPTION
**Pull request by shafimsp**
## Field Variants:

- Bottom Line (with Floating Label)

- Box (with Floating Label)

- Raised (Inline Only)

### CODE REVIEW

**Comment by shafimsp** [comment]
I have PR for each input component to support with field variants.

So please merge that too after this

- #1546 MdAutocomplete changes

- #1547 MdChips changes

- #1548 MdDatepicker changes

- #1549 MdField changes 

`Note: Please follow the same order while merging PRs to avoid conflict.`

**Comment by marcosmoura** [comment]
@shafimsp There is some issues with the theme colors:
screen shot 2018-02-28 at 15 21 48

**Comment by shafimsp** [comment]
Fixed issues with the theme colors
screenshot-localhost-8080-2018 03 03-18-58-16

screenshot-localhost-8080-2018 03 03-18-55-11

screenshot-localhost-8080-2018 03 03-18-54-45

**Comment by Samuell1** [comment]
After this change icons in selects are aligned to top @shafimsp 

obrazok

**Comment by shafimsp** [comment]
In material design doc, the icons are placed in vertically center

https://material.io/guidelines/components/text-fields.html#text-fields-input-types

**Comment by Samuell1** [comment]
In section Dropdown icon @shafimsp
obrazok

**Comment by marcos-hotmart** [comment]
@shafimsp This is definitely a bug on Select component. I will try to take a deep look on this.

**Comment by marcosmoura** [comment]
@shafimsp This is definitely a bug on Select component. I will try to take a deep look on this.

**Comment by shafimsp** [comment]
@Samuell1 @marcos-hotmart i have create a PR #1600 to fix this bug

**Pull request merged**
