### PR TITLE
fix(MdSelect): make options in disabled groups un-selectable and fix checkboxes

### LINKED ISSUE #1286: [MdSelect] options in disabled groups are selectable
### Steps to reproduce

Check the [official documentation](https://vuematerial.io/components/select), and scroll down to "Disabled" example area. Select the disabled groups.

### Which browser?

`vue-material@1.0.0-beta-7`

### What is expected?

Those options in disabled groups should be un-selectable.

### What is actually happening?

You can select the options in the disabled group.

### Reproduction Link

[official documentation](https://vuematerial.io/components/select)

### PR DESCRIPTION
**Pull request by VdustR**
* fix(MdSelect): make options in disabled groups un-selectable
    fix #1286
* fix(MdSelect): make multiple selection checkboxes effective
    before:
        peek 2017-12-11 10-56
    after:
        peek 2017-12-11 10-55

### CODE REVIEW

**Comment by marcosmoura** [comment]
@VdustR Can you resolve the conflicts?

**Comment by mdfcorp** [comment]
Is there any chance this could be merged? Or is there a workaround for the checkboxes not "passing" the selection for the meantime?

**Comment by VdustR** [comment]
Yes, I already resolved the conflict.

**Comment by nodetech-architecture** [comment]
This is not fixed this is still happening to me

**Pull request merged**
