### PR TITLE
Sass division migration: '/' => math.div()

### PR DESCRIPTION
**Pull request by Thunberg087**
- Fixed deprecated functionality with sass division
- Problem with current node-sass version so updated to latest version

### CODE REVIEW

**Comment by leandrohpa** [comment]
Any news?

**Comment by morewater** [comment]
No new releases ?

**Comment by christianopaets** [comment]
@Thunberg087 let's open this PR again, there is a hope that it will be merged

**Comment by RobineSavert** [comment]
Is this being solved sometime..? We want to migrate..

**Comment by okolomiets** [comment]
@Thunberg087  any update on the matter?

**Pull request closed without merging**
